/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.sealofthetime.nascts.server;

import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Arrays;
import java.util.Scanner;

import ru.sealofthetime.nascts.shared.Request;
import ru.sealofthetime.nascts.shared.Response;

public class ServerApplication {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        try{
            ServerSocket socket = new ServerSocket(0);
            System.out.println("Opened socket at " + socket.getLocalPort());
            Socket client = socket.accept();
            System.out.println("Connected from: " + client.getLocalAddress());

            Scanner sc = new Scanner(System.in);
            System.out.println("Starting to accept user input");
            while(sc.hasNext()){
                var res = sc.next();
                var bytes = new ByteArrayOutputStream();
                ObjectOutputStream out = new ObjectOutputStream(bytes);
                System.out.println("Sending " + res);
                out.writeObject(new Response(5, res));
                out.flush();
                byte[] obj = bytes.toByteArray();
                for (byte b : obj) System.out.print(b + " ");
                System.out.println("Length: " + obj.length);
                var os = new DataOutputStream(client.getOutputStream());
                os.writeInt(obj.length);
                os.write(obj);
            }
            ObjectInputStream in = new ObjectInputStream(client.getInputStream());
            Request req = (Request) in.readObject();
            System.out.println("Read request: " + Arrays.deepToString(req.data));
            
            socket.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
