/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.sealofthetime.nascts.shared;

import java.io.Serializable;

public class Response implements Serializable{
    private static final long serialVersionUID = 1L;
    
    public final int id;
    public final Object content;

    public Response(int id, Object content){
        this.id = id;
        this.content = content;
    }
}
